version: '3.0'
services:
  gateway:
    image: nginx:1.11
    ports:
      - 80:80
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - doc
      - users
      - filesystem
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    volumes:
      - ~/data/mongo:/data/db
    ports:
      - 27017:27017
  doc:
    container_name: doc
    build: ./doc/
    image: doc
    volumes:
      - ./doc/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
  users:
    container_name: users
    build: ./users/
    image: users
    volumes:
      - ./users/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongo
  filesystem:
    build: ./filesystem/
    image: filesystem
    container_name: filesystem
    environment:
      - NODE_ENV=local
    volumes:
      - ./filesystem/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    depends_on:
      - mongo