apps:
  - name: express-microservices
    script: server.js
    cwd: ./
    env_local:
      NODE_ENV: "development"
      PORT: 8080
      MONGO_URI: mongodb://mongo:27017/test
      APP_URL: http://localhost
      args:
        - environment:local